# This will do the same as Java CI build for develop, but this one is for manual purpose on specific branch.

name: Java CI - manual for branch

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Define branch name'     
        required: true
  pull_request:
    branches: [ develop ]
jobs:
  build:
    name: Build manual
    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch manual
      if: ${{ github.event.inputs.branch != '' }}
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.branch }}
    - name: Checkout branch PR
      if: ${{ github.event.inputs.branch == '' }}
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Maven tests
      #run: mvn test --fail-at-end --file Realization/backend/aggregator/pom.xml -Dspring.profiles.active=test
      run: |
        export MAVEN_HOME=/usr/bin/mvn
        echo $MAVEN_HOME
        mvn test -fn --file Realization/backend/aggregator/pom.xml -Dspring.profiles.active=test | perl -pe 'END { exit $status } $status=1 if /BUILD FAILURE/;'
    