# This will do the same as Java CI build for develop, but this one is for manual purpose on specific branch.

name: Java CI - manual for branch, test on PostgreSQL

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Define branch name'     
        required: true
      tests:
        type: boolean
        description: 'Run tests'
        required: true
        default: 'true'
  pull_request:
    branches: [ develop ]
jobs:
  build:
    name: Build manual
    runs-on: ubuntu-latest
    
    steps:
    - name: Start PostgreSQL on Ubuntu
      run: |
        sudo systemctl start postgresql.service
        pg_isready
    
    - name: Create additional user
      run: |
        sudo -u postgres psql --command="CREATE USER idmadmin PASSWORD 'idmadmin'" --command="\du"
    
    - name: Create additional database
      run: |
        sudo -u postgres createdb testdb --owner=idmadmin 
        PGPASSWORD=idmadmin

    - name: Checkout branch manual
      if: ${{ github.event.inputs.branch != '' }}
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.branch }}
    - name: Checkout branch PR
      if: ${{ github.event.inputs.branch == '' }}
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven with tests
#       if: ${{ github.event.inputs.tests == 'true' }}
      run: mvn -B --file Realization/backend/aggregator/pom.xml -Ptest-postgresql flyway:clean clean verify package
#     - name: Build with Maven without tests
#       if: ${{ github.event.inputs.tests == 'false' }}
#       run: mvn -B package --file Realization/backend/aggregator/pom.xml -Prelease -Dmaven.test.skip=true
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: idm.war
        path: Realization/backend/app/target
